<?php
    session_start();

    include 'viewcontroller.php';

//    $filenum = 10;

    //OLD WAY
    //$output = shell_exec('python /var/www/html/VMleak/external.py '.$filenum);//' 2>&1'
    //$series = shell_exec('python /var/www/html/VMleak/series.py '.$filenum);//' 2>&1'

    //BETTER WAY
    $series = generate_series_data(generate_full_file_list($filenum));
    $output = generate_delta( generate_full_file_list($filenum) ); 
?>
<!DOCTYPE html>
<html>
    <head>
        <title>Memory Leak Data:</title>    
        <link class="include" rel="stylesheet" type="text/css" href="/dist/jquery.jqplot.min.css" />
        <link type="text/css" rel="stylesheet" href="/dist/syntaxhighlighter/styles/shCoreDefault.min.css" />
        <link type="text/css" rel="stylesheet" href="/dist/syntaxhighlighter/styles/shThemejqPlot.min.css" />
	<link REL="StyleSheet" TYPE="text/css" HREF="style.css"> 
        <script class="include" type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type="text/javascript" src="script.js"></script>	
    </head>
    <body>
        <div id="cover"></div>
        <div id="header_bar"><img id="logo" src="/img/logo.png"></div>
        <center>
        <table id="main_table">
	    <tr>
		<td id="row"><div id="checkbox_group"></div><div><button value="add_file" type="button" onclick="add_to_checkboxes()">Add a File</div></td>	    
	        <td id="row">
		    <center><h1>Compared Data Useage Between Resets During Testing:</h1></center>
	            <center><div id="chart1" style="height:700px; width:1600px;"></div></center>
	            <div style="padding-top:20px"><button value="reset" type="button" onclick="plot1.resetZoom();">Reset Zoom</button></div>
                </td>
	    </tr>
        </table>
	</center>
	<script class="code" type="text/javascript">

            var plot1;

            function generate_checkbox(file_list){
                $.ajax({
		    data: {"function":"build_checkboxes", "file_list":"<?php echo generate_full_file_list($filenum); ?>"},
		    url: "viewcontroller.php",
		    method: "POST",
		    success: function(str){
		        $("#checkbox_group").html(str);  
		    }
		});
	    }

            function add_to_checkboxes(){
	        alert("UP IN HERERER");
	    }

	    /******************************************************************
	     * This looks for an event with a change in a checkbox group and
	     * will call php functions through ajax to get the updated data
	     * string and series string. var list is a string of file names
	     * generated by looking for all the "checked" boxes. Update_chart()
	     * is called on a successful return and will update the chart.
	     *****************************************************************/
	    $("#checkbox_group").change(function() { 
                var list = $("input[name=file_name]:checked").map( function () { return this.value; } ).get().join(" ");
                var delta = [];
		var series = "series";

                $.when(
		    $.ajax({
                        url: 'viewcontroller.php',
                        type: 'POST',
                        data: {'function': 'get_delta', 'file_list': list},
			success: function(str){
			    delta = JSON.parse(str);    
			}
                    }), 
		    $.ajax({
                        url: 'viewcontroller.php',
                        type: 'POST',
                        data: {'function': 'get_series', 'file_list': list},
			success: function(str){
			    /*TODO: Make this work... Using a Session variable for now...*/
			    //series = str;
			}
                    })
		).done(function() {
                    update_chart(delta, series);
                });
                
            });

 
	    /*************************************************************************
	     * Generates the graph on loading of the page
	     ************************************************************************/
            $(document).ready(function(){

                $.jqplot.config.enablePlugins = true;

		plot1 = $.jqplot ('chart1', <?php echo $output;?>, {     
                    highlighter: {
                        sizeAdjust: 14,
                        tooltipLocation: 'n',
                        tooltipAxes: 'y',
                        formatString:'#serieLabel# - %s',
                        useAxesFormatters: false
                    },
	            axes: {
                        xaxis: {
                            label: 'Resets per Test Run ',
		            tickInterval: 1
                        } 
                    },
	            grid: {
                        backgroundColor: '#EBEBEB',
                        borderWidth: 0,
                        gridLineColor: 'grey',
                        gridLineWidth: 1,
                        borderColor: 'black'
                    },
	            legend: {
                        show: true,
                        placement: 'inside'
                    },
                    cursor: {
                        show: true,
                        zoom: true
                    },
	            series:[ <?php echo $series;?> ], 
                });

                //OTHER FUNCTIONS TO LOAD AT THE START
		generate_checkbox('<?php echo generate_full_file_list($filenum);?>');
            });

            $(window).on('load', function() {
                setTimeout( function() { $("#cover").hide(); }, 1);
            });
          

            /******************************************************************
	     * Updates the chart with with new data.
	     *****************************************************************/
	    function update_chart(delta, series){
	        
	        updatePlot(delta, series);
		plot1.replot();
	    }

	    function updatePlot(delta, _series){
                console.log(<?php echo $file_list;?>);

                plot1 = $.jqplot('chart1', delta, {     
                    highlighter: {
                        sizeAdjust: 14,
                        tooltipLocation: 'n',
                        tooltipAxes: 'y',
                        formatString:'#serieLabel# - %s',
                        useAxesFormatters: false
                    },
	            axes: {
                        xaxis: {
                            label: 'Resets per Test Run ',
		            tickInterval: 1
                        } 
                    },
	            grid: {
                        backgroundColor: '#EBEBEB',
                        borderWidth: 0,
                        gridLineColor: 'grey',
                        gridLineWidth: 1,
                        borderColor: 'black'
                    },
	            legend: {
                        show: true,
                        placement: 'inside'
                    },
                    cursor: {
                        show: true,
                        zoom: true
                    },
	            series: [ <?php echo generate_series_data($_SESSION['file_list']);?> ]  
                });
            }

	    
        </script>


        <div><?php echo var_dump($_SESSION['file_list']); ?></div></br>
	<div><?php echo "OUTPUT:".$output; ?></div>
        <script class="include" type="text/javascript" src="/dist/jquery.jqplot.js"></script>
        <script type="text/javascript" src="/dist/syntaxhighlighter/scripts/shCore.min.js"></script>
        <script type="text/javascript" src="/dist/syntaxhighlighter/scripts/shBrushJScript.min.js"></script>
        <script type="text/javascript" src="/dist/syntaxhighlighter/scripts/shBrushXml.min.js"></script>

        <script class="include" type="text/javascript" src="/dist/plugins/jqplot.dateAxisRenderer.min.js"></script>
        <script class="include" type="text/javascript" src="/dist/plugins/jqplot.barRenderer.min.js"></script>
        <script class="include" type="text/javascript" src="/dist/plugins/jqplot.categoryAxisRenderer.min.js"></script>
        <script class="include" type="text/javascript" src="/dist/plugins/jqplot.cursor.min.js"></script>
        <script class="include" type="text/javascript" src="/dist/plugins/jqplot.highlighter.min.js"></script>
	
    </body>
</html>



